### ISSUE TITLE
Video doorbell

### ISSUE THREAD

**Issue by toshibochan** [lelandg/Raspberry-Pi-Security-Camera#21]
You can make other version to use as video doorbell? Push bottom, send picture to e-mail, make video call.

**Comment by toshibochan** [comment]
And use usb camera

**Comment by lelandg** [comment]
Thank you for the suggestions. I already have an issue for using a USB webcam. However, the video doorbell is a very good idea! :+1:

**Comment by lelandg** [comment]
Right now the security camera does not initiate any outgoing calls, so I would have to figure that out. I suspect it's possible, though. And of course we would have to configure the destination Linphone "number".

BTW, I welcome conversations in these issues (as suggested by GitHubs own guidelines).

**Comment by toshibochan** [comment]
Please if you can make I be happy :)

**Comment by lelandg** [comment]
I do not know for sure that it will be possible. However, I will look into this. (I have some other projects going, but I hope to work on this again soon.)

Yours is the first suggestion I have received, and I appreciate it, so will do my best. (As always.)

**Comment by lelandg** [comment]
Just an update: I have started researching this and found that it is possible to initiate an outgoing call from Python... at least according to the documentation. I am going to be busy today, but in honor of Pi Day (2016.03.14) I am going to spend my free time on this. 

Of course the "video doorbell" _will_ require a button, as you requested, and this will require changes to the hardware, but will be minor if you are familiar with breadboards/circuit assembly.

**Comment by toshibochan** [comment]
thanks! let me know when you start work on it! be great if use usb camera to, because the camera have mic, and the pi have 3.3mm audio out! 
because is video doorbell no need motion sensor just gpio push bottom.

**Comment by lelandg** [comment]
Yes, @toshibochan I'm actually hoping to work on this tomorrow, if I'm able. 

I understand you would like a button instead of a motion sensor. I think I will make the device do both. :+1: You will only need to set the PIRPIN=0 to disable the motion sensor. I will include details in the code. :)

**Comment by lelandg** [comment]
Also, @toshibochan I have not forgotten the USB camera. That is also a good idea, but as I mentioned before, I have another issue opened for that (here: [https://github.com/lelandg/Raspberry-Pi-Security-Camera/issues/19] )

**Comment by toshibochan** [comment]
If you use USB camera on the python file on the audio and video you have to add to receive video from the camera, mic from the camera and speaker I use 3.5 jack from the pi. But because pi is set audio to go to HDMI you have to force to go to 3.5 jack on terminal.

**Comment by toshibochan** [comment]
I will post my solution soon! But I having problems with USB camera ejecting after the call

**Comment by toshibochan** [comment]
By default output will be automatic (hdmi if hdmi supports audio, otherwise analogue). You can force it with:

 amixer cset numid=3 <n>
where n is 0=auto, 1=headphones, 2=hdmi.

**Comment by lelandg** [comment]
Thanks, Toshi! :)

FYI, I've been working on this today, but am going to have to stop for today (my hands bother me). I think I have the code implemented, have the button working for a doorbell, except I'm having trouble connecting with an outgoing call.

I know that it is possible, so there may be something I'm missing and I think I'll get there. :)

**Comment by toshibochan** [comment]
you have the documentation for me take look?

**Comment by toshibochan** [comment]
By default output will be automatic (hdmi if hdmi supports audio, otherwise analogue). You can force it with:

amixer cset numid=3 n
where n is 0=auto, 1=headphones, 2=hdmi.

**Comment by lelandg** [comment]
I'm sorry, but I somehow lost my script that prepares this script for release, so it will be tomorrow at the soonest. (I had a script that replaces all personal information with generic, e.g., 'youremail@example.com'. I use the personal info for testing. So I have to finish rewriting that script.)

Even then, I do not want to send you something that does not work, so hang in there. :+1: We'll get there soon. 

No other documentation has changed, yet. :)

**Comment by toshibochan** [comment]
I can't wait! Thanks!

**Comment by lelandg** [comment]
Hey @toshibochan , 

Just FYI--I got the device to call me today! But there was no video. I'm not sure why, but now it's telling me that the same camera I was using is not found. Yet I can otherwise use the camera and it is still working. Possibly I've installed/upgraded something that has broken Linphone, but at this point I'm a bit flabbergasted. Then again, perhaps it's one of those that I'll see first thing in the morning. :)

Anyway, I was excited when I heard the ringing sound in my headphones and was able to answer the call! So I think I'm very close.... :)

I have also been doing some fairly significant refactoring. I've removed (almost) all "print" statements and everything is going to the same Linphone log file. This is a big help and also results in cleaner-looking code.

So quite a few changes coming your way soon, I hope.

Thank you for your patience and enthusiasm. :+1:  :)

**Comment by toshibochan** [comment]
That's amazing! 
I'm just playing learning  how to do pushetta now! 
I wish I know how to do coding!

**Comment by lelandg** [comment]
But we also have chat and video (or we did earlier today--ha!). Can Pushetta do that? :) 

(Maybe they can... I just saw the site and it looks cool.)

Not so amazing when you know how. In fact, I'm slow in my older age... but can't help that. ;)

You can learn to code if you want to. I am totally self-educated except for 5 clock-hours and on-the-job training. What that means is I just read a lot of books about programming, typed in the examples and understood them enough to change them and play with them. I think it's a pretty good way to learn and you don't need a college degree! (I don't have one!) And it can be way more fun because you can study what you want to do. :) Of course these days you can find even better tutorials online!

So get some books or online tutorials and go for it!!! :100:

**Comment by lelandg** [comment]
Well, I _think_ this is good. Except my camera is not working with a script that I just used it with... (and I know that was working because we just ran it today on another RPi and it worked fine).

So, it seems I was right and something has changed my system somehow. 

If I came to him with a problem or question about development, a previous boss used to tell me, "Let me know when you find out!" So I will keep _you_ posted! :) :+1:

**Comment by toshibochan** [comment]
👍🏻👍🏻👍🏻thanks

**Comment by lelandg** [comment]
@toshibochan ,

Great news! I ran the new script, pushed the button and got a call on my PC (where I was logged into Linphone)!! And when I answered, _I had video_! :) That first session crashed, but I quickly found and fixed that problem, and guess what!?! It's working!!! (I'm checking it in right after I post this!)

We have a video doorbell, so I'm calling this version 0.2.0 since this is a significant feature.

Only thing is, I don't have audio from the camera to the client working and I'm not sure why. I'll look into this next, but for now, it is very useful because you could tell them that you can't hear them and then that you'll be there in a minute, or whatever. :)

Oh, and I just realized that I don't have the button in the Fritzing file, yet. I just connected it to GPIO 18 and GND. That's all there is to the hardware! Note that you can put that on a long wire so the button is outside but your RPi is inside where it's nice and dry. (Although, if the button can get wet, I would waterproof it somehow.

Likewise, you could mount the USB camera _in_ the door/wall/ceiling, etc.

Oh, yes, and the USB web cam is working great! :)

**Comment by toshibochan** [comment]
You are amazing! Where I can download?

**Comment by toshibochan** [comment]
I'm exciting to try! I been using my web cam on linphone but my USB camera keep loosing connection and linphone crashes! This happens to you?You know way?

**Comment by lelandg** [comment]
@toshibochan I just now checked it in! I always do a last-minute check and I found a bug, so fixed it. 

On the crashes, I have seen that happen a couple of times, _BUT_ after I fixed these latest bugs I have _NOT_ seen a crash. If you keep seeing them with this new version, will you please create a new issue and categorize it as a bug? I would appreciate it!

Thank you for your kind compliments, as always. :+1: :-) 

Let me know how it goes! I'm closing this issue, but I think we can still comment on it. ;-)

**Comment by lelandg** [comment]
This feature is implemented. Further comments are welcome, even though I'm closing the issue. :-) :+1:

**Comment by lelandg** [comment]
@toshibochan I also updated the ReadMe file. In addition to the snappy graphic (designed by my brother, Noel Green), I added a section on installation. Even if you've used the script you should check this out. Especially relating to the new utility scripts that are now included in the project. Very handy to use them. ;-)

BTW, this issue is now listed under the "Closed" tab. :+1:
