### ISSUE TITLE
erro start security_camera.py

### ISSUE THREAD

**Issue by toshibochan** [lelandg/Raspberry-Pi-Security-Camera#22]
Traceback (most recent call last):
  File "security_camera.py", line 119, in <module>
    from espeak import espeak
ImportError: No module named espeak

**Comment by lelandg** [comment]
I guess I didn't document everything very well. You simply need to do:

sudo apt-get install python-espeak

Thank you, I will document this and _then_ close this issue.

**Comment by lelandg** [comment]
@toshibochan , Thank you again. I have updated the ReadMe.md file. Please see there for instructions. After you install espeak, you also need the Python version of Linphone. I have included a link to that page because that in itself is rather detailed. And I figure that way, everyone will always install the latest version and then I will hear about any problems. ;)

If you hit more errors like this, feel free to re-open this issue (if it will let you, or create a new one if not).

If I can implement anything else, please let me know! :) :+1:
